import React, { useEffect, useMemo, useState } from 'react';
import { Link, Route, Routes, useNavigate } from 'react-router-dom';
import AdminPortal from './AdminPortal';
import { api } from './lib/api';

const WHATSAPP_NUMBER = (import.meta.env.VITE_WHATSAPP_NUMBER || '').replace(/\D/g, '');
const whatsappUrl = (text = 'Hi BasKarwaDo, mujhe help chahiye.') => WHATSAPP_NUMBER
  ? `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`
  : '/start';

const fallbackServices = [
  { slug:'money_recovery', title:'Paisa Wapas', short:'Refund, cancelled booking, failed service or money stuck.', icon:'₹', tone:'mint', starting_fee_paise:149900 },
  { slug:'after_sales', title:'After-Sales & Warranty', short:'Repair, warranty, replacement and service follow-up.', icon:'↻', tone:'blue', starting_fee_paise:99900 },
  { slug:'identity_repair', title:'Identity Repair', short:'PAN, Aadhaar, bank or document name / DOB mismatch.', icon:'ID', tone:'violet', starting_fee_paise:149900 },
  { slug:'move_life', title:'Move My Life', short:'Address updates after shifting home or city.', icon:'⌂', tone:'amber', starting_fee_paise:199900 },
  { slug:'marriage_sync', title:'Marriage Sync', short:'Name, address, nominee and record updates after marriage.', icon:'∞', tone:'rose', starting_fee_paise:249900 },
  { slug:'new_baby', title:'New Baby Setup', short:'Newborn document and benefit checklist.', icon:'+', tone:'cyan', starting_fee_paise:199900 },
  { slug:'after_loss', title:'After-Loss Admin', short:'Organise bank, insurance, account and family administration.', icon:'◌', tone:'slate', starting_fee_paise:999900 },
];

const fallbackQuestions = {
  money_recovery: [['merchant','Company / merchant / airline ka naam?'],['amount','Kitna amount atka hai?'],['issue_date','Issue / refund kab se pending hai?'],['reference','Order / booking / transaction ID?'],['summary','Short mein kya hua?']],
  after_sales: [['brand','Brand / seller ka naam?'],['product','Product aur model?'],['purchase_date','Purchase date?'],['warranty','Warranty active lag rahi hai?'],['summary','Exact problem kya hai?']],
  identity_repair: [['documents','Kaunse documents mismatch hain?'],['canonical_name','Correct legal name / detail kya hai?'],['blocked_action','Mismatch ki wajah se kya kaam atka hai?'],['summary','Mismatch briefly describe karein.']],
  move_life: [['from_city','Kahan se shift hue?'],['to_city','Kahan shift hue?'],['move_date','Move date?'],['records','Kin records ka address update chahiye?']],
  marriage_sync: [['marriage_date','Marriage date?'],['name_change','Name change karna hai?'],['address_change','Address change bhi hai?'],['records','Kaunse records update karne hain?']],
  new_baby: [['birth_date','Baby birth date?'],['city','Birth city?'],['hospital','Hospital / place of birth?'],['needs','Abhi kis document / benefit ki priority hai?']],
  after_loss: [['relation','Deceased se relation?'],['date','Date of death?'],['assets','Known banks / insurance / PF / investments?'],['nominee','Nominee details available hain?'],['summary','Sabse urgent admin concern kya hai?']],
};

const copy = {
  en:{ heroA:'Problem stuck?',heroB:'Just tell us.',hero:'Refund, product service, document mismatch or life-event paperwork — start on WhatsApp or web. We organise the next steps.',services:'Start with the problem. Not the department.',servicesText:'One backend handles many everyday admin problems. The intake adapts to the issue and creates a case-ready report.',whatsapp:'Start on WhatsApp',online:'Start online',how:'Three steps. No bureaucracy lecture.',navServices:'Services',navHow:'How it works',navTrack:'Track case' },
  hi:{ heroA:'काम अटका है?',heroB:'बस बताओ।',hero:'रिफंड, product service, document mismatch या life-event paperwork — WhatsApp या web पर शुरू करें। आगे की process हम organise करेंगे।',services:'शुरुआत problem से। Department से नहीं।',servicesText:'एक ही backend अलग-अलग everyday admin problems handle करता है। Intake problem के हिसाब से बदलता है और case-ready report बनाता है।',whatsapp:'WhatsApp पर शुरू करें',online:'Online शुरू करें',how:'तीन steps. बेकार bureaucracy lecture नहीं।',navServices:'सेवाएँ',navHow:'कैसे काम करता है',navTrack:'केस ट्रैक करें' },
  gu:{ heroA:'કામ અટક્યું છે?',heroB:'બસ કહો.',hero:'Refund, product service, document mismatch કે life-event paperwork — WhatsApp અથવા web પર શરૂ કરો. આગળની process અમે organise કરીશું.',services:'શરૂઆત problem થી. Department થી નહીં.',servicesText:'એક backend અલગ everyday admin problems handle કરે છે. Intake problem પ્રમાણે બદલાય છે અને case-ready report બનાવે છે.',whatsapp:'WhatsApp પર શરૂ કરો',online:'Online શરૂ કરો',how:'ત્રણ steps. ફાલતુ bureaucracy lecture નહીં.',navServices:'સેવાઓ',navHow:'કેવી રીતે કામ કરે',navTrack:'કેસ ટ્રેક કરો' },
};

const money = (paise=0)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format((paise||0)/100);
const labelFor = (question, locale) => question?.label?.[locale] || question?.label?.en || question?.[1] || '';

function Brand(){return <Link className="brand" to="/"><span className="brand-mark">B</span><span>BasKarwaDo</span></Link>}

function Header({locale,setLocale}){
  const t=copy[locale];
  return <header className="site-header"><div className="container header-inner"><Brand/><nav className="desktop-nav"><a href="/#services">{t.navServices}</a><a href="/#how">{t.navHow}</a><Link to="/track">{t.navTrack}</Link></nav><div className="header-actions"><select className="language-select" aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value)}><option value="en">EN</option><option value="hi">हिं</option><option value="gu">ગુજ</option></select><a className="btn btn-whatsapp btn-small desktop-whatsapp" href={whatsappUrl()} target={WHATSAPP_NUMBER?'_blank':undefined} rel="noreferrer">WhatsApp</a><Link className="btn btn-dark btn-small" to="/start">Start case</Link></div></div></header>
}

function ServiceCard({service,onStart}){return <button className={`service-card tone-${service.tone||'mint'}`} onClick={()=>onStart(service.slug)}><span className="service-icon">{service.icon||'→'}</span><span className="service-copy"><strong>{service.title}</strong><span>{service.short}</span><small>Starts at {money(service.starting_fee_paise||0)}</small></span><span className="service-arrow">↗</span></button>}

function Home({locale,services}){
  const t=copy[locale],nav=useNavigate();
  return <><main>
    <section className="hero-section"><div className="hero-orb orb-a"/><div className="hero-orb orb-b"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow-pill"><i/> INDIA-FIRST ASSISTANCE</span><h1>{t.heroA}<br/><span>{t.heroB}</span></h1><p>{t.hero}</p><div className="hero-actions"><a className="btn btn-whatsapp" href={whatsappUrl()} target={WHATSAPP_NUMBER?'_blank':undefined} rel="noreferrer">◉ {t.whatsapp}</a><Link className="btn btn-light" to="/start">{t.online} →</Link></div><div className="trust-row"><span>✓ Hindi · English · Gujarati</span><span>✓ Human-reviewed sensitive cases</span><span>✓ No PIN / password / OTP</span></div></div><div className="hero-console"><div className="console-bar"><span><i/><i/><i/></span><small>WHATSAPP INTAKE · LIVE DEMO</small></div><div className="chat-window"><div className="chat-head"><div className="chat-avatar">B</div><div><strong>BasKarwaDo</strong><small>typically replies instantly</small></div><b>✓</b></div><div className="chat-body"><div className="bubble in">Namaste 👋 Kya kaam atka hai?</div><div className="menu-message"><span>1 · Paisa Wapas</span><span>2 · Warranty</span><span>3 · Document mismatch</span><span>4 · Address shift</span></div><div className="bubble out">Mera ₹4,999 refund 14 din se pending hai.</div><div className="bubble in">Thik hai. Order screenshot bhej dijiye. Password/PIN/OTP kabhi mat bhejna.</div><div className="mini-report"><span>✓</span><div><small>CASE READINESS</small><strong>Evidence received · human review next</strong></div><b>80%</b></div></div></div><div className="floating-card fc-one"><small>ONE CASE ENGINE</small><strong>Web + WhatsApp</strong></div><div className="floating-card fc-two"><small>LANGUAGE</small><strong>EN · HI · GU</strong></div></div></div></section>

    <section className="proof-strip"><div className="container"><span>Problem-led intake</span><i/> <span>Private document vault</span><i/> <span>AI-assisted summaries</span><i/> <span>Human-owned actions</span></div></section>

    <section id="services" className="section services-section"><div className="container"><div className="section-heading"><div><span className="section-eyebrow">ONE BACKEND · MANY ENTRY DOORS</span><h2>{t.services}</h2></div><p>{t.servicesText}</p></div><div className="services-grid">{services.map(s=><ServiceCard key={s.slug} service={s} onStart={slug=>nav(`/start?service=${slug}`)}/>)}</div></div></section>

    <section id="how" className="section process-section"><div className="container"><div className="section-heading"><div><span className="section-eyebrow">HOW IT WORKS</span><h2>{t.how}</h2></div><p>AI is the intake assistant, not the decision-maker. Your case stays structured and a human owns sensitive execution.</p></div><div className="steps-grid"><article><b>01</b><div className="step-icon">⌁</div><h3>Tell us what is stuck</h3><p>Natural language on WhatsApp or a guided form on the website.</p></article><article><b>02</b><div className="step-icon">▤</div><h3>Case gets structured</h3><p>Relevant questions, documents, evidence, payment and AI-assisted summary in one case file.</p></article><article><b>03</b><div className="step-icon">✓</div><h3>Human team moves it forward</h3><p>Correct next action, follow-up, escalation or assisted workflow—without pretending AI is a lawyer or regulator.</p></article></div></div></section>

    <section className="section security-section"><div className="container security-grid"><div><span className="section-eyebrow">TRUST BY DESIGN</span><h2>Your documents are not a public upload folder.</h2><p>Evidence is stored privately. Staff access is authenticated. Customer tracking needs the case ID plus matching phone number.</p><Link className="text-link" to="/security">See security model →</Link></div><div className="security-cards"><article><span>01</span><strong>Private storage</strong><p>No public document URL.</p></article><article><span>02</span><strong>Audit timeline</strong><p>Operational actions are recorded.</p></article><article><span>03</span><strong>Human boundaries</strong><p>High-risk actions require review.</p></article><article><span>04</span><strong>Credential red line</strong><p>Never send PIN, CVV, OTP or passwords.</p></article></div></div></section>

    <section className="section cta-section"><div className="container cta-card"><div><span className="section-eyebrow">START WHERE YOU ARE COMFORTABLE</span><h2>WhatsApp first. Website when you want it.</h2><p>Both create the same BasKarwaDo case. Switch channels without creating a second backend record.</p></div><div className="cta-actions"><a className="btn btn-whatsapp" href={whatsappUrl()} target={WHATSAPP_NUMBER?'_blank':undefined} rel="noreferrer">Start on WhatsApp</a><Link className="btn btn-accent" to="/start">Start online →</Link></div></div></section>
  </main><Footer/></>;
}

function PageShell({title,subtitle,children}){return <><main className="page-main"><div className="container page-head"><Link className="back-link" to="/">← BasKarwaDo</Link><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="container">{children}</div></main><Footer/></>}

function PaymentButton({caseData,phone,onPaid}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  if (!caseData || caseData.payment_status==='paid') return caseData?.payment_status==='paid'?<div className="paid-badge">✓ Payment verified</div>:null;
  const loadScript=()=>new Promise((resolve,reject)=>{if(window.Razorpay)return resolve(true);const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve(true);s.onerror=()=>reject(new Error('Payment checkout could not load.'));document.body.appendChild(s);});
  const pay=async()=>{setBusy(true);setError('');try{await loadScript();const created=await api.createPaymentOrder(caseData.public_id,phone);const rzp=new window.Razorpay({key:created.key_id,amount:created.order.amount,currency:created.order.currency,name:'BasKarwaDo',description:caseData.service?.title||'Case assistance',order_id:created.order.id,prefill:created.customer,theme:{color:'#101828'},handler:async(response)=>{try{await api.verifyPayment({public_id:caseData.public_id,...response});onPaid?.();}catch(e){setError(e.message);}}});rzp.open();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <div className="payment-box"><div><small>ASSISTANCE FEE</small><strong>{money(caseData.fee_paise)}</strong><span>Pay securely via Razorpay</span></div><button className="btn btn-dark" onClick={pay} disabled={busy}>{busy?'Preparing…':'Pay now →'}</button>{error&&<p className="payment-error">{error}</p>}</div>;
}

function StartCase({services,locale}){
  const query=new URLSearchParams(window.location.search),initial=query.get('service')||'';
  const [service,setService]=useState(initial),[step,setStep]=useState(initial?2:1),[details,setDetails]=useState({name:'',phone:'',email:'',locale}),[answers,setAnswers]=useState({}),[files,setFiles]=useState([]),[created,setCreated]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const selected=services.find(s=>s.slug===service);
  const q=selected?.questions?.length?selected.questions:(fallbackQuestions[service]||[]).map(([key,label])=>({key,label:{en:label,hi:label,gu:label}}));

  const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{const first=await api.createCase({...details,service_slug:service,source:'web'});let result=await api.addAnswers(first.data.public_id,details.phone,answers);for(const file of files){await api.uploadDocument(first.data.public_id,details.phone,file,'evidence');}if(files.length){result=await api.trackCase(first.data.public_id,details.phone);}setCreated(result.data);setStep(4);}catch(err){setError(err.message);}finally{setBusy(false);}};
  const chooseFiles=(event)=>{const chosen=Array.from(event.target.files||[]).slice(0,5);setFiles(chosen);};

  if(created)return <PageShell title="Case created" subtitle="Save the case ID. You can continue on WhatsApp or track online."><div className="success-layout"><div className="success-card"><span className="success-mark">✓</span><span className="section-eyebrow">CASE READY</span><h2>{created.public_id}</h2><p>{created.summary||'Your intake has been saved for review.'}</p><div className="case-stats"><span><small>Status</small><strong>{created.status_label}</strong></span><span><small>Readiness</small><strong>{created.readiness_score}%</strong></span><span><small>Documents</small><strong>{created.documents_count||files.length}</strong></span></div><PaymentButton caseData={created} phone={details.phone} onPaid={async()=>setCreated((await api.trackCase(created.public_id,details.phone)).data)}/><div className="success-actions"><Link className="btn btn-dark" to="/track">Track case</Link><a className="btn btn-whatsapp" href={whatsappUrl(`Hi BasKarwaDo, mera case ${created.public_id} hai.`)} target={WHATSAPP_NUMBER?'_blank':undefined} rel="noreferrer">Continue on WhatsApp</a></div></div><aside className="next-card"><span className="section-eyebrow">WHAT HAPPENS NEXT</span><ol><li><b>Evidence analysis</b><span>Uploaded documents are queued for structured extraction.</span></li><li><b>Human review</b><span>A team member checks the case before sensitive action.</span></li><li><b>Status updates</b><span>Track online with case ID + phone; WhatsApp updates can be enabled.</span></li></ol></aside></div></PageShell>;

  return <PageShell title="Start a case" subtitle="Usually 2–5 minutes. Short answers are fine; evidence can be uploaded securely."><div className="wizard-progress">{[1,2,3].map((n,i)=><React.Fragment key={n}><span className={step>=n?'active':''}>{n}</span>{i<2&&<i/>}</React.Fragment>)}</div>
    {step===1&&<div className="wizard-panel"><div className="form-head"><span className="section-eyebrow">STEP 1</span><h2>What is stuck?</h2><p>Choose the problem. You do not need to know the department or process.</p></div><div className="wizard-services">{services.map(s=><ServiceCard key={s.slug} service={s} onStart={slug=>{setService(slug);setStep(2)}}/>)}</div></div>}
    {step===2&&<form className="wizard-panel form-grid" onSubmit={e=>{e.preventDefault();setStep(3)}}><div className="form-head"><span className="service-tag">{selected?.title}</span><h2>Who should we update?</h2><p>Use the mobile number you will use for tracking. Do not share passwords, PINs, CVV or OTP.</p></div><label>Full name<input required value={details.name} onChange={e=>setDetails({...details,name:e.target.value})} placeholder="Rahul Patel"/></label><label>WhatsApp / mobile<input required inputMode="tel" value={details.phone} onChange={e=>setDetails({...details,phone:e.target.value})} placeholder="+91 98xxxxxx"/></label><label>Email (optional)<input type="email" value={details.email} onChange={e=>setDetails({...details,email:e.target.value})} placeholder="you@example.com"/></label><label>Preferred language<select value={details.locale} onChange={e=>setDetails({...details,locale:e.target.value})}><option value="en">English</option><option value="hi">Hindi</option><option value="gu">Gujarati</option></select></label><div className="form-actions"><button type="button" className="btn btn-light" onClick={()=>setStep(1)}>Back</button><button className="btn btn-dark">Continue →</button></div></form>}
    {step===3&&<form className="wizard-panel form-grid" onSubmit={submit}><div className="form-head"><span className="service-tag">{selected?.title}</span><h2>Case details</h2><p>We ask only the fields needed for this workflow.</p></div>{q.map(question=><label key={question.key} className={question.key==='summary'?'full-field':''}>{labelFor(question,details.locale)}{question.key==='summary'?<textarea rows="4" value={answers[question.key]||''} onChange={e=>setAnswers({...answers,[question.key]:e.target.value})} required/>:<input value={answers[question.key]||''} onChange={e=>setAnswers({...answers,[question.key]:e.target.value})} required={['amount','summary'].includes(question.key)}/>}</label>)}<label className="file-drop full-field"><span><b>Supporting evidence (optional)</b><small>PDF, JPG, PNG, WEBP · up to 8 MB each · max 5 here</small></span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={chooseFiles}/><strong>{files.length?`${files.length} file(s) selected`:'Choose files'}</strong></label><label className="consent-check full-field"><input type="checkbox" required/><span>I am authorised to share this information for assistance. I will not upload passwords, PINs, CVV, UPI PIN, netbanking credentials or OTPs.</span></label>{error&&<div className="error-box full-field">{error}</div>}<div className="form-actions full-field"><button type="button" className="btn btn-light" onClick={()=>setStep(2)}>Back</button><button className="btn btn-dark" disabled={busy}>{busy?'Creating secure case…':'Create case →'}</button></div></form>}
  </PageShell>;
}

function TrackCase(){
  const [form,setForm]=useState({publicId:'',phone:''}),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async(e)=>{e?.preventDefault();setBusy(true);setError('');try{const r=await api.trackCase(form.publicId,form.phone);setData(r.data);}catch(err){setData(null);setError(err.message);}finally{setBusy(false);}};
  return <PageShell title="Track your case" subtitle="Your case ID and matching mobile number are required."><form className="track-card" onSubmit={load}><label>Case ID<input required value={form.publicId} onChange={e=>setForm({...form,publicId:e.target.value.toUpperCase()})} placeholder="BKW-XXXXXXXX"/></label><label>Mobile number<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+91..."/></label><button className="btn btn-dark" disabled={busy}>{busy?'Checking…':'Check status'}</button>{error&&<div className="error-box full-field">{error}</div>}</form>{data&&<div className="tracking-layout"><section className="tracking-main"><div className="status-card"><div><span className={`status-chip status-${data.status}`}>{data.status_label}</span><h2>{data.service?.title}</h2><p>{data.summary}</p></div><div className="status-score"><strong>{data.readiness_score}%</strong><span>case readiness</span></div></div>{data.customer_report?.recommended_next_step&&<div className="customer-report"><span className="section-eyebrow">CURRENT RECOMMENDATION</span><h3>{data.customer_report.recommended_next_step}</h3>{data.customer_report.warnings?.length>0&&<ul>{data.customer_report.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul>}</div>}{data.updates?.length>0&&<div className="updates-card"><h3>Updates from the team</h3>{data.updates.map((u,i)=><article key={i}><span/><div><p>{u.message}</p><small>{new Date(u.created_at).toLocaleString('en-IN')}</small></div></article>)}</div>}</section><aside className="tracking-side"><div className="side-fact"><small>Case ID</small><strong>{data.public_id}</strong></div><div className="side-fact"><small>Documents</small><strong>{data.documents_count}</strong></div><div className="side-fact"><small>Payment</small><strong>{data.payment_status}</strong></div><div className="side-fact"><small>Fee</small><strong>{money(data.fee_paise)}</strong></div><PaymentButton caseData={data} phone={form.phone} onPaid={load}/></aside></div>}</PageShell>;
}

function StaticPage({type}){
  const pages={
    privacy:{title:'Privacy & data handling',intro:'BasKarwaDo processes case information only to provide the assistance the customer requests.',sections:[['What we collect','Contact details, case answers, documents or screenshots you choose to share, payment status, and operational audit data.'],['What we do not ask for','Do not send passwords, UPI PIN, ATM PIN, card CVV, netbanking credentials or OTPs.'],['How data is used','To structure the case, extract relevant facts, support human review, communicate case status and process payment. AI processing should be configured with data-minimising settings and only on customer-provided case evidence.'],['Retention','Production deployment should define category-specific retention periods and a deletion workflow. Do not keep identity or financial documents indefinitely just because storage is cheap.']]},
    security:{title:'Security model',intro:'The product is designed around a private case vault, authenticated staff access and strict automation boundaries.',sections:[['Private evidence','Customer files are stored on a private filesystem disk and served only through authenticated admin endpoints.'],['Access control','Staff log in with hashed passwords and receive expiring bearer tokens. Role and active status are checked server-side.'],['Webhook integrity','Meta WhatsApp webhooks use X-Hub-Signature-256 verification; Razorpay webhooks use HMAC-SHA256 verification and idempotent event IDs.'],['AI boundary','AI may classify, extract and summarise. Human review owns sensitive, legal, financial or high-risk actions.']]},
    terms:{title:'Service terms — product draft',intro:'This is a launch-ready product draft and should be reviewed by Indian counsel before public deployment.',sections:[['Assistance, not impersonation','BasKarwaDo helps organise information, prepare steps and track execution. Customer-authenticated actions remain with the customer where required.'],['No guaranteed outcome','Refunds, complaints, claims, document changes and third-party service outcomes depend on the responsible merchant, authority, regulator or institution.'],['Accuracy','Customers are responsible for providing truthful information and documents they are authorised to share.'],['Regulated work','Legal representation, regulated financial advice or other licensed activity must be performed by an appropriately qualified partner where required.']]},
  }; const p=pages[type];
  return <PageShell title={p.title} subtitle={p.intro}><div className="policy-grid">{p.sections.map(([h,b])=><article key={h}><h2>{h}</h2><p>{b}</p></article>)}</div></PageShell>;
}

function Footer(){return <footer className="footer"><div className="container footer-top"><div><Brand/><p>Problem WhatsApp karo. Aage hum organise karenge.</p></div><div className="footer-links"><div><strong>Product</strong><Link to="/start">Start case</Link><Link to="/track">Track case</Link><Link to="/admin">Staff login</Link></div><div><strong>Trust</strong><Link to="/privacy">Privacy</Link><Link to="/security">Security</Link><Link to="/terms">Terms</Link></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} BasKarwaDo</span><span>Assistance platform · Sensitive actions remain human-reviewed.</span></div></footer>}

export default function App(){
  const [locale,setLocale]=useState(localStorage.getItem('bkw_locale')||'en');
  const [services,setServices]=useState(fallbackServices);
  useEffect(()=>{localStorage.setItem('bkw_locale',locale)},[locale]);
  useEffect(()=>{api.services().then(r=>{if(r.data?.length)setServices(r.data.map((s,i)=>({...fallbackServices[i%fallbackServices.length],...s}))) }).catch(()=>{})},[]);
  const isAdmin=window.location.pathname.startsWith('/admin');
  return <div className="app">{!isAdmin&&<Header locale={locale} setLocale={setLocale}/>}<Routes><Route path="/" element={<Home locale={locale} services={services}/>}/><Route path="/start" element={<StartCase services={services} locale={locale}/>}/><Route path="/track" element={<TrackCase/>}/><Route path="/privacy" element={<StaticPage type="privacy"/>}/><Route path="/security" element={<StaticPage type="security"/>}/><Route path="/terms" element={<StaticPage type="terms"/>}/><Route path="/admin" element={<AdminPortal/>}/><Route path="*" element={<PageShell title="Page not found"><Link className="btn btn-dark" to="/">Go home</Link></PageShell>}/></Routes></div>;
}
