[program:baskrwado-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/baskrwado/backend/artisan queue:work --queue=default --sleep=2 --tries=3 --timeout=120 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/baskrwado/backend/storage/logs/worker.log
stopwaitsecs=130
